spring:
    datasource:
        password: '@Safe96441'
        url: jdbc:mysql://localhost:3306/serverdb
        username: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        show-sql: true

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5332/customer
#     username: postgres
#     password: "#!***mn17***"
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect
#         format_sql: true
#     show-sql: true
#   main:
#     web-application-type: servlet
